--create table
CREATE TABLE DEVELOPER 
(   DEV_ID NUMBER(2) PRIMARY KEY 
    , DEV_NAME VARCHAR2(50 CHAR) NOT NULL 
    , DEV_SURNAME VARCHAR2(50 CHAR)	NOT NULL 
    , DEV_BIRTH_DATE DATE 
    , DEV_START_DATE DATE 
    , DEV_MARRY_STATUS CHAR(1 CHAR) 
    , CREATED_BY VARCHAR2(50 CHAR) NOT NULL 
    , CREATED_DATE TIMESTAMP NOT NULL 
);

CREATE TABLE MARRIES 
(   MR_ID NUMBER(2) PRIMARY KEY 
    , MR_DEV_ID	NUMBER(2) NOT NULL --FK Table DEVELOPER
    , MR_SPOUSE_NAME VARCHAR2(50 CHAR) NOT NULL 
    , MR_SPOUSE_SURNAME	VARCHAR2(50 CHAR) NOT NULL 
    , MR_STATUS	VARCHAR2(20 CHAR) 
    , CREATED_BY VARCHAR2(50 CHAR) NOT NULL 
    , CREATED_DATE TIMESTAMP NOT NULL 
    , CONSTRAINT FK_MR_DEVID FOREIGN KEY (MR_DEV_ID) REFERENCES DEVELOPER(DEV_ID) 
);

CREATE TABLE STATUS 
(   STAT_ID	NUMBER(2) PRIMARY KEY 
    , STAT_NAME VARCHAR2(20 CHAR) NOT NULL 
    , STAT_START_DATE DATE NOT NULL 
    , STAT_END_DATE	DATE NOT NULL 
    , CREATED_BY VARCHAR2(50 CHAR) NOT NULL 
    , CREATED_DATE TIMESTAMP NOT NULL 
);

CREATE TABLE APPLICATION 
(   APP_ID NUMBER(2) PRIMARY KEY 
    , APP_NAME	VARCHAR2(20 CHAR) NOT NULL 
    , APP_STAT_ID NUMBER(2) NOT NULL --FK Table STATUS 
    , APP_DEV_ID NUMBER(2) NOT NULL --FK Table DEVELOPER 
    , CREATED_BY VARCHAR2(50) NOT NULL 
    , CREATED_DATE TIMESTAMP NOT NULL 
    , CONSTRAINT FK_APPSTAT FOREIGN KEY (APP_STAT_ID) REFERENCES STATUS(STAT_ID) 
    , CONSTRAINT FK_APPDEV FOREIGN KEY (APP_DEV_ID) REFERENCES DEVELOPER(DEV_ID) 
);

--1. Insert data into table developer
INSERT INTO DEVELOPER
VALUES ('1', 'Manchima', 'Wongsuwannasarn', TO_DATE('1992/05/01','yyyy/mm/dd'), TO_DATE('2019/01/01','yyyy/mm/dd'), 's', 'Admin', SYSTIMESTAMP);
INSERT INTO DEVELOPER (DEV_ID, DEV_NAME, DEV_SURNAME, CREATED_BY, CREATED_DATE)
VALUES ('2','Sunisa', 'Supee', 'Admin', SYSTIMESTAMP);

SELECT*FROM DEVELOPER ;

--2. Update data in table developer change DEV_MARRY_STATUS of Toom from "Single" to "Married"
UPDATE DEVELOPER
SET DEV_BIRTH_DATE = TO_DATE('1991/10/15','yyyy/mm/dd')
    , DEV_START_DATE = TO_DATE('2019/01/15','yyyy/mm/dd')
    , DEV_MARRY_STATUS = 's'
WHERE DEV_ID = 2 ;

INSERT INTO DEVELOPER
VALUES ('3', 'Nutwara', 'Phuchanha', TO_DATE('1992/01/23','yyyy/mm/dd'), TO_DATE('2019/01/31','yyyy/mm/dd'), 's', 'Admin', SYSTIMESTAMP);
INSERT INTO DEVELOPER
VALUES ('4', 'Maree', 'Wongsuwannasarn', NULL, TO_DATE('2019/01/31','yyyy/mm/dd'), 's', 'Admin', SYSTIMESTAMP);

--การเรียงลำดับ
SELECT*FROM DEVELOPER ORDER BY DEV_ID; 
--เรียงมากหาน้อย
SELECT*FROM DEVELOPER ORDER BY DEV_ID DESC;

UPDATE DEVELOPER
SET DEV_MARRY_STATUS = 'M'
WHERE DEV_ID = 3 ;

--3. Delete data in table developer remove developer "Maree" 
DELETE FROM DEVELOPER
WHERE DEV_ID = 4 ;

--Table : MARRIES
--1. Insert data into table marries
INSERT INTO MARRIES
VALUES ('1', '1', 'Anantachai', 'Phuchanha', 'Married', 'Admin', SYSTIMESTAMP);

SELECT*FROM MARRIES ;

SELECT*FROM STATUS ;

--Table : STATUS
--1. Insert data into table status
INSERT INTO STATUS
VALUES ('1', 'Planning', TO_DATE('2019/01/01','yyyy/mm/dd'), TO_DATE('9999/12/31','yyyy/mm/dd'), 'Admin', SYSTIMESTAMP);
INSERT INTO STATUS
VALUES ('2', 'Get requirement', TO_DATE('2019/01/01','yyyy/mm/dd'), TO_DATE('9999/12/31','yyyy/mm/dd'), 'Admin', SYSTIMESTAMP);
INSERT INTO STATUS
VALUES ('3', 'System design', TO_DATE('2019/01/01','yyyy/mm/dd'), TO_DATE('9999/12/31','yyyy/mm/dd'), 'Admin', SYSTIMESTAMP);
INSERT INTO STATUS
VALUES ('4', 'Development', TO_DATE('2019/01/01','yyyy/mm/dd'), TO_DATE('9999/12/31','yyyy/mm/dd'), 'Admin', SYSTIMESTAMP);
INSERT INTO STATUS
VALUES ('5', 'Testing', TO_DATE('2019/01/01','yyyy/mm/dd'), TO_DATE('9999/12/31','yyyy/mm/dd'), 'Admin', SYSTIMESTAMP);
INSERT INTO STATUS
VALUES ('6', 'Implementation', TO_DATE('2019/01/01','yyyy/mm/dd'), TO_DATE('9999/12/31','yyyy/mm/dd'), 'Admin', SYSTIMESTAMP);

--2. Insert new data into table status
INSERT INTO STATUS
VALUES ('7', 'Mantenance', TO_DATE('2019/02/20','yyyy/mm/dd'), TO_DATE('9999/12/31','yyyy/mm/dd'), 'Admin', SYSTIMESTAMP);

--Table : APPLICATION
--1. Insert data into table application
SELECT*FROM APPLICATION ;

ALTER TABLE APPLICATION --DROP FK
DROP CONSTRAINT FK_APPDEV;

ALTER TABLE APPLICATION
MODIFY APP_DEV_ID VARCHAR2(10 CHAR);

INSERT INTO APPLICATION
VALUES ('1', 'Shopee', '1', '1', 'Admin', SYSTIMESTAMP);
INSERT INTO APPLICATION
VALUES ('2', 'Lazada', '3', '1,2', 'Admin', SYSTIMESTAMP);
INSERT INTO APPLICATION
VALUES ('3', 'Facebook', '4', '2,3', 'Admin', SYSTIMESTAMP);
INSERT INTO APPLICATION
VALUES ('4', 'Hr', '1', '7', 'Admin', SYSTIMESTAMP);

UPDATE APPLICATION
SET APP_STAT_ID = '7'
    , APP_DEV_ID = '1,2,3'
WHERE APP_ID = 4 ;

--Work with SQL
--1. Retrieve data of developer name Sunisa
SELECT *
FROM DEVELOPER
WHERE DEV_NAME = 'Sunisa' ;

--2. Retrieve data of developer whose status is Married
SELECT *
FROM DEVELOPER
WHERE DEV_MARRY_STATUS = 'M';

--3. Retrieve full name of developer whose birth year in 1992
--SELECT EXTRACT(YEAR FROM DEV.DEV_BIRTH_DATE), DEV.DEV_BIRTH_DATE, DEV_NAME, DEV_SURNAME ,DEV_NAME || ' ' ||  DEV_SURNAME AS FULL_NAME
--FROM DEVELOPER DEV
--WHERE EXTRACT(YEAR FROM DEV.DEV_BIRTH_DATE) = 1992;

SELECT DEV_NAME || ' ' ||  DEV_SURNAME AS FULL_NAME
FROM DEVELOPER DEV
WHERE EXTRACT(YEAR FROM DEV.DEV_BIRTH_DATE) = 1992;


--4. Retrieve full name of developer whose surname have 'an' in surname order by full name DESC
+SELECT DEV_NAME || ' ' ||  DEV_SURNAME AS FULL_NAME
FROM DEVELOPER DEV
WHERE DEV_SURNAME LIKE '%an%'
ORDER BY FULL_NAME DESC;

--5. Retrieve data of developer whose length of surname < 9
SELECT DEV_ID, DEV_NAME, DEV_SURNAME
FROM DEVELOPER
WHERE LENGTH(DEV_SURNAME) < 9;

--6. Retrieve status name when active in this period (where sysdate between start and end) order by status name
SELECT STAT_NAME || ' ' ||  STAT_NAME AS STATUS_NAME
FROM STATUS
WHERE sysdate BETWEEN STAT_START_DATE AND STAT_END_DATE 
ORDER BY STATUS_NAME;

--7.Count number of Single developer
SELECT COUNT(*) COUNT
FROM DEVELOPER
WHERE DEV_MARRY_STATUS = 's';

--8. Sum age of all developer (find age from current year - birth year)
SELECT * FROM DEVELOPER;

SELECT EXTRACT(YEAR FROM SYSDATE), EXTRACT(YEAR FROM DEV_BIRTH_DATE)
FROM DEVELOPER;

SELECT (EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DEV_BIRTH_DATE))
FROM DEVELOPER;

SELECT SUM(EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DEV_BIRTH_DATE)) AS TOTAL_AGE
FROM DEVELOPER;

--9. Average age of all developer (find age from current year - birth year)
SELECT TRUNC(AVG(EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DEV_BIRTH_DATE))) AS AVG_AGE
FROM DEVELOPER;

--10. Max and Min of status start date from status table
SELECT *
FROM STATUS;

SELECT MAX(STAT_START_DATE) AS MAX_START_DATE
FROM STATUS;

SELECT MIN(STAT_START_DATE) AS MIN_START_DATE
FROM STATUS;

SELECT MAX(STAT_START_DATE) AS MAX_START_DATE ,MIN(STAT_START_DATE) AS MIN_START_DATE
FROM STATUS;
